# Generated by Django 2.0.2 on 2018-03-18 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_user', models.CharField(max_length=255, null=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('source_fund', models.CharField(max_length=255)),
                ('source_amount', models.PositiveIntegerField()),
                ('expend_in', models.CharField(max_length=255)),
                ('expend_amount', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('verified', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True, default='')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(blank=True, default='')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='Not Selected', max_length=50)),
                ('contact_number', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
