# Generated by Django 2.0.2 on 2018-03-18 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180318_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expend',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 18, 9, 12, 27, 311929, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expend',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 3, 18, 9, 12, 46, 615343, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 18, 9, 13, 9, 222838, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 3, 18, 9, 13, 19, 839004, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
