# Generated by Django 2.0.5 on 2018-05-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180318_0913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expend',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='user', max_length=50),
        ),
    ]
