# Generated by Django 2.0.5 on 2018-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180506_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('co-admin', 'Co-Admin'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
