# Generated by Django 2.0.2 on 2018-03-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_user', models.CharField(max_length=255, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('source_fund', models.CharField(max_length=255)),
                ('source_amount', models.PositiveIntegerField()),
                ('expend_in', models.CharField(max_length=255)),
                ('expend_amount', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('verified', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255)),
            ],
        ),
    ]
